In [1]:
# import libraries
import numpy as np
import cv2 as cv

In [2]:
# read in single test image
img = cv.imread("/home/leo/Documents/UNI/ICDS/Groupwork/Group1/data/test/normal/IM-0115-0001.jpeg", cv.IMREAD_GRAYSCALE)
print(img.shape)

(1858, 2090)


In [61]:
class conv_layer:
    def __init__(self, in_dim, conv_size=(3,3), conv_num=4):
        self.conv_size = conv_size
        self.conv_num = conv_num
        self.conv_kernels = [None] * self.conv_num
        for i in range(0, self.conv_num):
            self.conv_kernels[i] = np.empty(conv_size)
        self.in_dim = in_dim
        self.out_dim = ( self.conv_num, self.in_dim[0] - (conv_size[0] - 1), self.in_dim[1] - (self.conv_size[1] - 1))
        
    def forward(self, img):
        out_img = np.empty(self.out_dim)
        for i in range(0, self.conv_num):
            for ii in range(0, self.out_dim[0]):
                for iii in range(0, self.out_dim[1]):
                    out_img[i, ii, iii] = np.sum(img[ii:ii+self.conv_size[0], iii:iii+self.conv_size[1]] * self.conv_kernels[i])
        return out_img
    
    def get_out_dim(self):
        return self.out_dim

In [68]:
# test conv layer
a = np.zeros((6,6))
index = 0
for i in range(0,a.shape[0]):
    for ii in range(0,a.shape[1]):
        a[i, ii] = index
        index += 1

print("input before conv")
print(a)
c = conv_layer(in_dim=a.shape, conv_size=(3,3), conv_num=3)
print("expected out dim")
print(c.get_out_dim())
d = c.forward(a)
print("output conv shape")
print(d.shape)
print("output conv")
print(d)


input before conv
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
expected out dim
(3, 4, 4)
output conv shape
(3, 4, 4)
output conv
[[[2.52420000e+004 2.76230000e+004 3.00040000e+004 3.23850000e+004]
  [3.95280000e+004 4.19090000e+004 4.42900000e+004 4.66710000e+004]
  [5.38140000e+004 5.61950000e+004 5.85760000e+004 6.09570000e+004]
  [1.20000000e+001 1.30000000e+001 1.40000000e+001 1.50000000e+001]]

 [[0.00000000e+000 2.44616802e-316 4.89233605e-316 7.33850407e-316]
  [1.46770081e-315 1.71231762e-315 1.95693442e-315 2.20155122e-315]
  [2.93540163e-315 3.18001843e-315 3.42463523e-315 3.66925204e-315]
  [1.20000000e+001 1.30000000e+001 1.40000000e+001 1.50000000e+001]]

 [[0.00000000e+000 2.44613957e-316 4.89227913e-316 7.33841870e-316]
  [1.46768374e-315 1.71229770e-315 1.95691165e-315 2.20152561e-315]
  [2.93536748e-315 3.17998144e-315 3.42459539e-315 3.66920935e-315]


In [75]:
class max_pooling_layer:
    def __init__(self, in_dim, pooling_size=(3,3)):
        self.pooling_size = pooling_size
        self.in_dim = in_dim
        self.out_dim = (self.in_dim[0], self.in_dim[1] - (self.pooling_size[0] - 1), self.in_dim[2] - (self.pooling_size[1] - 1))
        
    def forward(self, img):
        out_img = np.empty(self.out_dim)
        
        for i in range(0, self.out_dim[2]):
            for ii in range(0, self.out_dim[0]):
                for iii in range(0, self.out_dim[1]):
                    out_img[ii,iii] = np.max(img[ii:ii+self.pooling_size[0], iii:iii+self.pooling_size[1], i])
        return out_img

In [76]:
# test pool layer
a = np.zeros((3, 5, 5))
index = 0
for i in range(0,a.shape[1]):
    for ii in range(0,a.shape[2]):
        a[:, i, ii] = index
        index += 1
print("input before pool")
print(a)
c = max_pooling_layer(in_dim=a.shape, pooling_size=(3,3))
d = c.forward(a)
print("output pool")
print(d)

input before pool
[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]

 [[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]
  [20. 21. 22. 23. 24.]]]
output pool
[[[12. 12. 12.]
  [17. 17. 17.]
  [22. 22. 22.]]

 [[12. 12. 12.]
  [17. 17. 17.]
  [22. 22. 22.]]

 [[12. 12. 12.]
  [17. 17. 17.]
  [22. 22. 22.]]]


In [88]:
# currently only ReLU activation function hardcoded
class activation_layer:
    def __init__(self, in_dim):
        self.in_dim = in_dim

    def forward(self, img):
        out_img = np.stack(np.vectorize(self.relu)(img), axis=0)
        return out_img

    def relu(self, el):
        return(np.maximum(0, el))

In [93]:
# test activation layer
a = np.zeros((2, 3, 3))
index = -4
for i in range(0,a.shape[1]):
    for ii in range(0,a.shape[2]):
        a[:, i, ii] = index
        index += 1
print("input before activation")
print(a)
r = activation_layer(a.shape)
b = r.forward(a)
print(b)


input before activation
[[[-4. -3. -2.]
  [-1.  0.  1.]
  [ 2.  3.  4.]]

 [[-4. -3. -2.]
  [-1.  0.  1.]
  [ 2.  3.  4.]]]
[[[0. 0. 0.]
  [0. 0. 1.]
  [2. 3. 4.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [2. 3. 4.]]]


In [ ]:
class fully_connected_layer:
    def __init__(self, in_dim):
        pass

In [ ]:
# test them in succesion

