### Compare Own PCA and libaries

In [23]:
import pandas as pd
import numpy as np
import os

import the data

In [24]:
# Task 1: Load data sets
data_directory = "data"
dataframe = pd.read_csv(os.path.join(data_directory, "data.csv"))
dataframe

  Unnamed: 0  gene_0    gene_1    gene_2    gene_3     gene_4  gene_5  \
0   sample_0     0.0  2.017209  3.265527  5.478487  10.431999     0.0   
1   sample_1     0.0  0.592732  1.588421  7.586157   9.623011     0.0   
2   sample_2     0.0  3.511759  4.327199  6.881787   9.870730     0.0   
3   sample_3     0.0  3.663618  4.507649  6.659068  10.196184     0.0   
4   sample_4     0.0  2.655741  2.821547  6.539454   9.738265     0.0   
5   sample_5     0.0  3.467853  3.581918  6.620243   9.706829     0.0   
6   sample_6     0.0  1.224966  1.691177  6.572007   9.640511     0.0   
7   sample_7     0.0  2.854853  1.750478  7.226720   9.758691     0.0   
8   sample_8     0.0  3.992125  2.772730  6.546692  10.488252     0.0   
9   sample_9     0.0  3.642494  4.423558  6.849511   9.464466     0.0   

     gene_6    gene_7  gene_8  ...  gene_20521  gene_20522  gene_20523  \
0  7.175175  0.591871     0.0  ...    4.926711    8.210257    9.723516   
1  6.816049  0.000000     0.0  ...    4.593372  

In [25]:
# Drop column 'Unnamed'
if 'Unnamed: 0' in dataframe.columns:
    df = dataframe.drop(['Unnamed: 0'], axis=1)
df

gene_0    gene_1    gene_2    gene_3     gene_4  gene_5    gene_6  \
0       0.0  2.017209  3.265527  5.478487  10.431999     0.0  7.175175   
1       0.0  0.592732  1.588421  7.586157   9.623011     0.0  6.816049   
2       0.0  3.511759  4.327199  6.881787   9.870730     0.0  6.972130   
3       0.0  3.663618  4.507649  6.659068  10.196184     0.0  7.843375   
4       0.0  2.655741  2.821547  6.539454   9.738265     0.0  6.566967   
..      ...       ...       ...       ...        ...     ...       ...   
796     0.0  1.865642  2.718197  7.350099  10.006003     0.0  6.764792   
797     0.0  3.942955  4.453807  6.346597  10.056868     0.0  7.320331   
798     0.0  3.249582  3.707492  8.185901   9.504082     0.0  7.536589   
799     0.0  2.590339  2.787976  7.318624   9.987136     0.0  9.213464   
800     0.0  2.325242  3.805932  6.530246   9.560367     0.0  7.957027   

       gene_7  gene_8  gene_9  ...  gene_20521  gene_20522  gene_20523  \
0    0.591871     0.0     0.0  ...    4.926711    8.210257    9.723516   
1    0.000000     0.0     0.0  ...    4.593372    7.323865    9.740931   
2    0.452595     0.0     0.0  ...    5.125213    8.127123   10.908640   
3    0.434882     0.0     0.0  ...    6.076566    8.792959   10.141520   
4    0.360982     0.0     0.0  ...    5.996032    8.891425   10.373790   
..        ...     ...     ...  ...         ...         ...         ...   
796  0.496922     0.0     0.0  ...    6.088133    9.118313   10.004852   
797  0.000000     0.0     0.0  ...    6.371876    9.623335    9.823921   
798  1.811101     0.0     0.0  ...    5.719386    8.610704   10.485517   
799  0.000000     0.0     0.0  ...    5.785237    8.605387   11.004677   
800  0.000000     0.0     0.0  ...    6.403075    8.594354   10.243079   

     gene_20524  gene_20525  gene_20526  gene_20527  gene_20528  gene_20529  \
0      7.220030    9.119813   12.003135    9.650743    8.921326    5.286759   
1      6.256586    8.381612   12.674552   10.517059    9.397854    2.094168   
2      5.401607    9.911597    9.045255    9.788359   10.090470    1.683023   
3      8.942805    9.601208   11.392682    9.694814    9.684365    3.292001   
4      7.181162    9.846910   11.922439    9.217749    9.461191    5.110372   
..          ...         ...         ...         ...         ...         ...   
796    4.484415    9.614701   12.031267    9.813063   10.092770    8.819269   
797    6.555327    9.064002   11.633422   10.317266    8.745983    9.659081   
798    3.589763    9.350636   12.180944   10.681194    9.466711    4.677458   
799    4.745888    9.626383   11.198279   10.335513   10.400581    5.718751   
800    9.139459   10.102934   11.641081   10.607358    9.844794    4.550716   

     gene_20530  
0      0.000000  
1      0.000000  
2      0.000000  
3      0.000000  
4      0.000000  
..          ...  
796    0.000000  
797    0.000000  
798    0.586693  
799    0.000000  
800    0.000000  

[801 rows x 20531 columns]

In [26]:
pca_data = df.values
pca_data

array([[ 0.        ,  2.01720929,  3.26552691, ...,  8.92132623,
         5.28675919,  0.        ],
       [ 0.        ,  0.59273209,  1.58842082, ...,  9.39785429,
         2.09416849,  0.        ],
       [ 0.        ,  3.51175898,  4.32719872, ..., 10.09046974,
         1.68302267,  0.        ],
       ...,
       [ 0.        ,  3.24958187,  3.70749166, ...,  9.46671072,
         4.6774575 ,  0.5866927 ],
       [ 0.        ,  2.59033853,  2.78797567, ..., 10.40058062,
         5.71875068,  0.        ],
       [ 0.        ,  2.32524248,  3.80593214, ...,  9.84479363,
         4.55071601,  0.        ]])

In [27]:
# Check for zero or near-zero variance features
variances = np.var(pca_data, axis=0)
near_zero_var_indices = np.where(variances < 1e-6)[0]
if near_zero_var_indices.size > 0:
    print("Features with near-zero variance found. Removing them...")
    data = np.delete(pca_data, near_zero_var_indices, axis=1)

Features with near-zero variance found. Removing them...


In [28]:
# Scale the data
scaled_data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)

In [29]:
# own PCA for two components
from dataimport import random_sample
from our_pca import our_pca

scaled_dataframe = pd.DataFrame(scaled_data)

n_components = 2
data = random_sample(scaled_dataframe, 801, 2000)
own_pca = our_pca(data, n_components)

In [30]:
own_eigenvalues, own_eigenvectors = own_pca

# Display eigenvalues and eigenvectors
print("Eigenvalues:")
print(own_eigenvalues)

print("Eigenvectors:")
print(own_eigenvectors)

Eigenvalues:
[206.86693114+0.j 165.57631936+0.j]
Eigenvectors:
[[-0.01596773+0.j  0.01437181+0.j]
 [-0.02751726+0.j  0.03040981+0.j]
 [ 0.00551735+0.j -0.00641813+0.j]
 ...
 [ 0.00563532+0.j  0.02141901+0.j]
 [-0.02779518+0.j -0.01059999+0.j]
 [-0.01481744+0.j -0.00888603+0.j]]


In [31]:
#put own eigenvectors into a DataFrame while only using the real numbers from the given complex numbers
own_eigenvectors_df = pd.DataFrame(own_eigenvectors)
own_eigenvectors_df
own_eig_df = pd.DataFrame()
own_eig_df['eigenvec_0'] = own_eigenvectors_df[0].to_numpy().real
own_eig_df['eigenvec_1'] = own_eigenvectors_df[1].to_numpy().real
own_eig_df

eigenvec_0  eigenvec_1
0      -0.015968    0.014372
1      -0.027517    0.030410
2       0.005517   -0.006418
3       0.038399   -0.000634
4      -0.020905    0.030226
...          ...         ...
1995    0.027155   -0.000815
1996    0.028434    0.012058
1997    0.005635    0.021419
1998   -0.027795   -0.010600
1999   -0.014817   -0.008886

[2000 rows x 2 columns]

#### own PCA and statsmodels
comparison statsmodels on smaller dataset

In [32]:
from statsmodels.multivariate.pca import PCA

In [33]:
# Perform PCA with two components
pca_stats_sample = PCA(data, ncomp=2)
pca_stats_sample

Principal Component Analysis(nobs: 801, nvar: 2000, transformation: Standardize (Correlation), normalization: True, number of components: 2, SVD, id: 0x1ca36cd4150)

In [34]:
# Get the eigenvalues and eigenvectors
eigenvalues_sample = pca_stats_sample.eigenvals
eigenvectors_sample = pca_stats_sample.eigenvecs

# Display eigenvalues and eigenvectors
print("Eigenvalues:")
print(eigenvalues_sample)

print("Eigenvectors:")
print(eigenvectors_sample)

Eigenvalues:
0    165493.544908
1    132461.055491
Name: eigenvals, dtype: float64
Eigenvectors:
      eigenvec_0  eigenvec_1
0      -0.015968    0.014372
1      -0.027517    0.030410
2       0.005517   -0.006418
3       0.038399   -0.000634
4      -0.020905    0.030226
...          ...         ...
1995    0.027155   -0.000815
1996    0.028434    0.012058
1997    0.005635    0.021419
1998   -0.027795   -0.010600
1999   -0.014817   -0.008886

[2000 rows x 2 columns]


check if the outputs from our PCA and statsmodels are the same

In [35]:
# Check if the eigenvectors contain the same values
check_df = abs(eigenvectors_sample - own_eig_df)
check_df

eigenvec_0    eigenvec_1
0     5.551115e-17  4.076600e-16
1     1.179612e-16  1.144917e-16
2     1.552578e-16  2.029626e-16
3     2.983724e-16  1.688103e-16
4     2.255141e-16  8.326673e-17
...            ...           ...
1995  9.367507e-17  1.479936e-16
1996  8.326673e-17  9.887924e-17
1997  1.734723e-18  3.122502e-17
1998  2.081668e-17  8.500145e-17
1999  3.295975e-17  3.469447e-17

[2000 rows x 2 columns]

In [36]:
# Check if values in the DataFrame are nearly zero
is_close_to_zero = np.isclose(check_df, 0.0, atol=1e-15)
is_close_to_zero

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       ...,
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [37]:
# Check if all values in the array are True
np.all(is_close_to_zero)

True

#### own PCA and sklearn
comparison sklearn on smaller dataset

In [45]:
from sklearn.decomposition import PCA as PCA_sk

In [48]:
# define number of components as 2 
pca_sample=PCA_sk(n_components=2)
pca_sample.fit(data)

PCA(n_components=2)

In [49]:
eigenvectors_sk_sample = pca_sample.components_
eigenvectors_sk_sample

array([[ 0.01596773,  0.02751726, -0.00551735, ..., -0.00563532,
         0.02779518,  0.01481745],
       [ 0.01437182,  0.03040981, -0.00641812, ...,  0.02141901,
        -0.01059999, -0.00888603]])

In [50]:
#put own eigenvectors into a DataFrame while only using the real numbers from the given complex numbers
eigenvectors_sk_df = pd.DataFrame(eigenvectors_sk_sample.transpose())
# Rename columns
eigenvectors_sk_df = eigenvectors_sk_df.set_axis(['eigenvec_0', 'eigenvec_1'],  axis=1)
eigenvectors_sk_df

eigenvec_0  eigenvec_1
0       0.015968    0.014372
1       0.027517    0.030410
2      -0.005517   -0.006418
3      -0.038399   -0.000634
4       0.020905    0.030226
...          ...         ...
1995   -0.027155   -0.000815
1996   -0.028434    0.012058
1997   -0.005635    0.021419
1998    0.027795   -0.010600
1999    0.014817   -0.008886

[2000 rows x 2 columns]

check if the outputs from our PCA and sklearn are the same

In [51]:
# Check if the eigenvectors contain the same values
check_df2 = abs(eigenvectors_sk_df - own_eig_df)
check_df2

eigenvec_0    eigenvec_1
0       0.031935  3.431493e-10
1       0.055035  7.774965e-11
2       0.011035  6.850724e-10
3       0.076797  1.680955e-09
4       0.041810  1.429446e-09
...          ...           ...
1995    0.054311  1.160546e-09
1996    0.056869  3.561980e-09
1997    0.011271  3.045419e-10
1998    0.055590  1.047548e-09
1999    0.029635  2.493615e-09

[2000 rows x 2 columns]

In [52]:
# Check if values in the DataFrame are nearly zero
is_close_to_zero2 = np.isclose(check_df2, 0.0, atol=1e-15)
is_close_to_zero2

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])